title: Whiteside Advisory
email: jeff@wh.itesi.de
description: >
  Personal perspectives on security leadership, governance, risk management, and real-world compliance challenges.

baseurl: ""

author:
  name: Jeff Whiteside
  email: jeff@wh.itesi.de
  phone: 
url: "https://wh.itesi.de" # your base hostname & protocol
timezone: America/Chicago

# Build settings
plugins_dir:
  - jekyll-feed
  - jekyll-seo-tag

# Social profiles (if you have them)
social:
  twitter: 
  linkedin: 
  github: 

# SEO and meta
locale: "en_US"
logo: /images/avatar.jpg
lang: en_US

future: true
